export enum Constants {
  ON_CHANGE_EMAIL = 'ON_CHANGE_EMAIL',
  ON_CHANGE_PASSWORD = 'ON_CHANGE_PASSWORD',
  LOG_IN = 'LOG_IN',
  LOG_OUT = 'LOG_OUT',
  LOAD_MORE = 'LOAD_MORE',
  HANDLE_REFRESH = 'HANDLE_REFRESH',
}
