export enum Constants {
  LOG_IN = 'LOG_IN',
  LOG_OUT = 'LOG_OUT',
  REFRESH = 'REFRESH',
  START_LOADING = 'START_LOADING',
  STOP_LOADING = 'STOP_LOADING',
  ADD_PAGE = 'ADD_PAGE',
  ADD_DATA = 'ADD_DATA',
}
